import {Image} from 'react-bootstrap';
import { Container, Row, Col } from 'react-bootstrap';

export const Home = (props) => {

    return (
        <div>
           <h1 className="main-page-header-left">Quick-React</h1>

           <p>Quick-React is a Website and a VS Code extension developed to make the development of hook-based React projects faster, by eliminating many of the manual setup steps.  Although scripts such as <strong>create-react-app</strong>, initialize a great deal of the scaffolding for a typical SPA Website, project setup could benefit from additional configuration assistance, as long as the process is simple, intuitive, and fast.</p>

            <p>Quick-React addresses this need by utilizing a simple JSX-style markup format, in a simple to understand outline format, that is parsed into a component data-structure by the Quick-React Website or VS Code extension.  This data is then used to generate either a ZIP archive of the starting React directories and files, when the Quick-React Website is used, or is injected directly into your project via the VS Code extension when working locally.</p>

            <p>Quick-React does not currently support class-based components.  It generates scaffolding for functional components and utilizes JavaScript arrow functions in most cases for components and handler functions.  Quick-React does not generate CSS or Sass coding and does not modify CSS boilerplate code generated by create-react-app. Additional, npm or yarn JSON files are not accessed or modified.  The use of supporting add-on modules to a React project still needs to be performed manually at this time.</p>

            <p>Please review the documentation link above to see if Quick-React can be helpful to you as a tool.  Register for an account if you wish to use this Website to manage your project documents.  the Quick-React <b>Visual Studio Code extension</b> is also a great resource for generating content quickly to kick-off your React projects.</p>

            <p>Send me your feedback to let me know what you think about this tool and what improvements can be made.</p>

            <p>I would like to extend a special thanks to <strong><a href="hhttps://generalassemb.ly/about" target="_blank" rel="noreferrer">General Assembly</a></strong> for providing me the time to work on this personal project.</p>

            <p>&nbsp;</p>

        </div>
    )
} 

export default Home;